__log_info_native("akhenaten: load modules started")

include(":akhenaten.conf")
include(":hotkeys.conf")

import common
import camera
import game
import math
import rating_points
import animal_herds
import gods
import city
import city_kingdome
import building_prototype
import bazaar_prototype
import city_finance
import city_ratings
import city_festival
import city_monuments
import city_labor
import images
import city_sounds
import buildings
import building_house
import building_mastaba
import building_pyramid
import building_farm
import building_fort
import building_education
import building_palace
import building_temple
import building_shrine
import building_statue
import building_mansion
import building_workshop
import building_temple_complex
import building_entertainment
import building_firehouse
import building_hunting_lodge
import building_pottery
import building_mine_copper
import building_mine_gold
import building_mine_gems
import building_granary
import building_health
import building_architect_post
import overlays
import images
import population
import images_remap
import imagepaks
import missions
import figures
import localization
import building_menu
import desirability
import kingdome_relation
import floodplain
import clouds
import ui
import houses
import routing
import economic
import migration
import eventmsg_phrase_auto
import figure_names_en
import music
import invasions
import enemies
import sentiment
import empire
import empire_city_prototype
import console_commands
import malaria_risk
import player
import mods
import empire_map
